# Generated by Django 3.2.15 on 2022-09-07 08:25

from django.db import migrations, models
import django.db.models.deletion
import merchant.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='merchant', serialize=False, to='user.user')),
                ('abn_verified', models.BooleanField(default=False)),
                ('abn', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[merchant.validators.checkABN], verbose_name='ABN')),
                ('merchant_name', models.CharField(max_length=50, verbose_name='Merchant Name')),
                ('merchant_intro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Merchant Introduction')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
    ]
