# Generated by Django 3.2.15 on 2022-10-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='has_shipped',
            field=models.BooleanField(default=False, verbose_name='Shipping'),
        ),
    ]
