# Generated by Django 3.2.15 on 2022-10-11 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 2, 0, 50, 152923, tzinfo=utc)),
        ),
    ]
