# Generated by Django 3.2.15 on 2022-09-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_orderdetail_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quality',
            new_name='quantity',
        ),
    ]
