# Generated by Django 3.2.15 on 2022-10-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_orderdetail_has_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
