# Generated by Django 3.2.15 on 2022-10-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_orderdetail_stripe_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='session_id',
            field=models.CharField(default='pre', max_length=70),
            preserve_default=False,
        ),
    ]
