# Generated by Django 3.2.15 on 2022-10-11 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_orderdetail_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
