# Generated by Django 3.2.15 on 2022-10-11 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_orderdetail_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 2, 13, 57, 584764)),
        ),
    ]
