# Generated by Django 3.2.15 on 2022-10-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_orderdetail_notes'),
        ('payments', '0010_alter_orderdetail_created_on'),
    ]

    operations = [
    ]
