# Generated by Django 3.2.15 on 2022-10-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20221019_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
