# Generated by Django 3.2.15 on 2022-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bike_longDescription',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_power',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_weight',
        ),
        migrations.AddField(
            model_name='bike',
            name='throttle',
            field=models.CharField(default='', help_text='e.g. Half Twist Throttle', max_length=20, verbose_name='Throttle'),
        ),
        migrations.AddField(
            model_name='bike',
            name='tires',
            field=models.CharField(default='', help_text='e.g. Kenda 24 x 24', max_length=20, verbose_name='Tires'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default='', help_text='e.g. 460 Jones St', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(default='', help_text='e.g. Hornsby', max_length=20, verbose_name='Suburb'),
        ),
    ]
