# Generated by Django 3.2.15 on 2022-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
    ]
