# Generated by Django 4.1 on 2022-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bike_is_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='is_rent',
            field=models.BooleanField(default=False, verbose_name='This product is for rent'),
        ),
    ]
