# Generated by Django 3.2.15 on 2022-10-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221027_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='throttle',
            new_name='bike_throttle',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='tires',
            new_name='bike_tires',
        ),
    ]
