# Generated by Django 3.2.15 on 2022-10-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_address_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='view_count',
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name='view count'),
        ),
    ]
