# Generated by Django 4.1 on 2022-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_bike_is_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_brand',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=200, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='AVAILABLE', max_length=11, verbose_name='status'),
        ),
    ]
