# Generated by Django 4.1 on 2022-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_bike_bike_brand_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_longDescription',
            field=models.CharField(default=None, max_length=200, verbose_name='LongDescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_power',
            field=models.CharField(default=None, max_length=200, verbose_name='Power'),
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_weight',
            field=models.CharField(default=None, max_length=200, verbose_name='Weight'),
        ),
    ]
